version: '3.3'

services:
  pg:
    image: postgres:9.6-alpine
    env_file:
      - ./db.env
    volumes:
      - pg-data:/var/lib/postgresql/data

  webapp:
    image: jfahrer/demo_web_app:latest
    ports:
      - 9292:9292
    env_file:
      - ./app.env


volumes:
  pg-data:
